feat: 커밋 변경 내용을 change 단위로 분리
git-marvel/commit-guardians-client pull request #30
Opened 2024-11-05 11:24 UTC by shkimjune

# 이슈

🔗이슈 링크: [#2](https://github.com/git-marvel/commit-guardians-client/issues/2)

# 요약

* 연속적인 변화가 있는 문단을 change로 정의
* 변화가 있는 문단을 기준으로 나누었습니다.

# 작업내용

- [ ] 변경 내용을 "diff" 키워드 기준으로 나누기

- [ ] 연속적인 변화가 있는 문단을 기준으로 change 분리

- [ ] 커밋 리스트 내용에 추가
- [ ] changes 전달 구조 변경
삭제된 코드들을 개행문자로 구분지어 하나의 문자열로 구성하기 (+추가된 코드도 동일)

- [ ] changes 로직을 file단위로 나눠 entities 폴더(fsd 폴더 구조)에 생성

# PR 체크 사항

## 주의 사항

- [ ] PR 크기는 300~500줄로 하되 최대 1000줄 미만으로 합니다.
- [ ] conflict를 모두 해결하고 PR을 올려주세요.

## PR 전 체크리스트

- [ ] 가장 최신 브랜치를 pull 하였습니다.
- [ ] base 브랜치명을 확인하였습니다.
- [ ] 코드 컨벤션을 모두 확인하였습니다.
- [ ] 브랜치명을 확인하였습니다.
- [ ] 작업 중 dependency 변경사항이 있는 경우 안내해주세요!

---

## 리뷰 반영사항

- [ ]

2024-11-05 13:53 UTC, GreenteaHT commented on src/entities/change/services/index.js
> +  }
for문으로 표현하는 것과 map으로 표현하는 것 중 저는 map을 선호하는데, 여러분은 어떤 것이 더 좋으신가요?
```suggestion
  codeListPerFile.map((commitCode) => {
    const result = makeAChange(commitCode);
    commitChangesMap.set(result.fileName, result.changes);
  }
```

2024-11-05 13:53 UTC, GreenteaHT commented on src/entities/change/changeEntity.js
> +  let keyContent =
keyConent가 재할당되는 부분이 없는 것 같은데, let을 사용하신 이유가 있으실까요?

2024-11-06 05:25 UTC, shkimjune commented on src/entities/change/services/index.js
> +  }
map을 사용할 때 코드를 읽을 때 바로 의미를 파악할 수 있어서 좋네요! 수정하겠습니다~!

2024-11-06 05:27 UTC, shkimjune commented on src/entities/change/changeEntity.js
> +  let keyContent =
이전에 분기로 나눠서 재할당했었다가 다시 코드를 수정하는 과정에서 그대로 let으로 남겨져 있는 것 같네요..! 수정하겠습니다!

2024-11-06 05:46 UTC, howyoujini requested changes

2024-11-06 05:46 UTC, howyoujini commented on src/entities/change/services/index.js
> +  const commitUrl = `https://api.github.com/repos/${commitData.owner}/${commitData.repo}/commits/${commitData.ref}`;
이 부분은 철환님이 작성하신 부분을 응용하면 좋겠네요!
https://github.com/git-marvel/commit-guardians-client/pull/29/commits/592c00301f68af5ff0fbabd078440b01a9018e61

2024-11-06 05:46 UTC, howyoujini commented on src/entities/change/services/index.js
> +    },
이 부분도 이전 Merge 참고해보면 좋을 것 같습니다!
https://github.com/git-marvel/commit-guardians-client/pull/29/commits/592c00301f68af5ff0fbabd078440b01a9018e61

2024-11-06 05:58 UTC, shkimjune commented on src/entities/change/services/index.js
> +  const commitUrl = `https://api.github.com/repos/${commitData.owner}/${commitData.repo}/commits/${commitData.ref}`;
api 가 동일한 부분이 많아서 따로 분리하여 다시 수정해보도록 하겠습니다!

2024-11-06 06:00 UTC, shkimjune commented on src/entities/change/services/index.js
> +    },
넵 이 부분도 api 요청 함수를 따로 분리하여 작성하는 것이 좋겠네요!

2024-11-06 09:04 UTC, howyoujini requested changes
조금만 수정부탁드려요~~!

2024-11-06 09:04 UTC, howyoujini commented on src/pages/Home/api/getCommitList.js
> +          )
이제 **await** 키워드를 쓰기로 결정했으니까, 이번에 이왕 변경하는 코드이므로 **await** 으로 변경하는게 어떨까요?

https://www.notion.so/greentea-ice/b38d8f4bcd7e45888c3ee39a1d136bf6?pvs=4#93544b99d47c4388b63915d3ce38f8bb

```js
if (lastPageNumber > 1) {
      const fetchPromises = [];
      for (let page = 2; page <= lastPageNumber; page++) {

	     const commitPromise = async () => {
			   const res =  await fetchCommits(commitListUrl, page)
		     return res.json();
		   }
      
        fetchPromises.push(commitPromise);
      }
```

2024-11-06 09:05 UTC, GreenteaHT commented on src/pages/Home/api/getCommitList.js
> +};
commit 변경 사항을 가져오는 거기 때문에 single Commit보다는 diff 관련한 이름이였으면 좋겠습니다!

2024-11-06 10:48 UTC, shkimjune commented on src/pages/Home/api/getCommitList.js
> +};
확실히 diff키워드를 넣는 것이 함수를 이해가 잘 될 것 같습니다!

2024-11-06 11:28 UTC, howyoujini commented on src/pages/Home/index.jsx
> +      <button type="submit">api 요청</button>;
`;` 만 제거해서 올려주세요~!

2024-11-06 11:29 UTC, shkimjune commented on src/pages/Home/index.jsx
> +      <button type="submit">api 요청</button>;
넵 바로 제거하겠습니다..!

2024-11-06 11:30 UTC, howyoujini approved these changes
수고하셨습니다!

2024-11-06 12:13 UTC, GreenteaHT approved these changes

2024-11-06 12:13 UTC, GreenteaHT commented
수고하셨습니다!

2024-11-06 12:13 UTC, howyoujini approved these changes

2024-11-06 12:14 UTC, merged